# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 06 Dec 2013 05:47:39 +0000
*	@ALL	1
*	@user	8
*	lconcha	4
*	soporte	4
