<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: soporte
 * Date: Fri, 30 Jan 2015 16:12:42 -0600
 */

$conf['title'] = 'fMRILAB Dokuwiki';
$conf['start'] = 'Inicio';
$conf['lang'] = 'es';
$conf['tagline'] = 'Porque es bueno ser curioso...';
$conf['license'] = '';
$conf['youarehere'] = 1;
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['manager'] = 'mantenimiento';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['subscribers'] = 1;
$conf['notify'] = 'lconcha@gmail.com';
$conf['registernotify'] = 'lconcha@gmail.com';
$conf['mailfrom'] = 'inb.fmrilab@gmail.com';
$conf['mailprefix'] = '[dokuwiki]';
$conf['plugin']['markdownextra']['frontmatter'] = 1;
$conf['plugin']['aceeditor']['default'] = 1;
$conf['plugin']['aceeditor']['highlight'] = 1;
$conf['plugin']['aceeditor']['colortheme'] = 'solarized_dark';
$conf['plugin']['aceeditor']['latex'] = 1;
$conf['plugin']['aceeditor']['markdown'] = 1;
$conf['plugin']['swiftmail']['smtp_host'] = 'smtp.gmail.com';
$conf['plugin']['swiftmail']['smtp_port'] = 465;
$conf['plugin']['swiftmail']['smtp_ssl'] = '4';
$conf['plugin']['swiftmail']['auth_user'] = 'inb.fmrilab';
$conf['plugin']['swiftmail']['auth_pass'] = 'Imagen04';
$conf['plugin']['swiftmail']['localdomain'] = '172.24.80.100';

// end auto-generated content
